// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/list-belt-diagnostics.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-belt-diagnostics.ts
var list_belt_diagnostics_default = defineTool({
  name: "list_belt_diagnostics",
  title: "List belt diagnostics",
  description: "List the signed-in user's saved conveyor belt diagnostic records, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum records to return (default 10)."),
    status: z.string().trim().min(1).max(50).optional().describe("Filter by record status, e.g. 'open'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("belt_diagnostics").select("id, created_at, location, tracking_direction, severity, cause, status, notes").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { diagnostics: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-belt-diagnostic.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^3.25.76";
var create_belt_diagnostic_default = defineTool2({
  name: "create_belt_diagnostic",
  title: "Create belt diagnostic",
  description: "Save a new conveyor belt diagnostic record for the signed-in user, including cause and recommendations.",
  inputSchema: {
    location: z2.string().trim().min(1).max(200).describe("Where on the conveyor the issue was observed."),
    tracking_direction: z2.string().trim().min(1).max(50).describe("Direction the belt is mistracking, e.g. 'left', 'right', 'none'."),
    severity: z2.string().trim().min(1).max(50).describe("Severity, e.g. 'low', 'medium', 'high', 'critical'."),
    cause: z2.string().trim().min(1).max(1e3).describe("Diagnosed root cause."),
    recommendations: z2.array(z2.string().trim().min(1).max(500)).min(1).max(20).describe("Recommended corrective actions."),
    belt_saver_benefits: z2.array(z2.string().trim().min(1).max(500)).max(20).optional().describe("How BeltSaver would address this issue."),
    notes: z2.string().trim().max(2e3).optional().describe("Additional free-form notes."),
    status: z2.string().trim().min(1).max(50).optional().describe("Record status (default 'open').")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("belt_diagnostics").insert({
      user_id: ctx.getUserId(),
      location: input.location,
      tracking_direction: input.tracking_direction,
      severity: input.severity,
      cause: input.cause,
      recommendations: input.recommendations,
      belt_saver_benefits: input.belt_saver_benefits ?? [],
      notes: input.notes ?? null,
      status: input.status ?? "open"
    }).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Diagnostic saved (id ${data.id}).` }],
      structuredContent: { diagnostic: data }
    };
  }
});

// src/lib/mcp/tools/list-equipment-diagnostics.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_equipment_diagnostics_default = defineTool3({
  name: "list_equipment_diagnostics",
  title: "List equipment diagnostics",
  description: "List the signed-in user's heavy equipment diagnostic sessions, newest first, optionally filtered by make or equipment type.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Maximum records to return (default 10)."),
    make: z3.string().trim().min(1).max(100).optional().describe("Filter by equipment make, e.g. 'CAT'."),
    equipment_type: z3.string().trim().min(1).max(100).optional().describe("Filter by equipment type, e.g. 'Excavator'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, make, equipment_type }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("equipment_diagnostics").select("id, created_at, equipment_type, make, model, symptoms, diagnosis, status").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (make) query = query.ilike("make", make);
    if (equipment_type) query = query.ilike("equipment_type", equipment_type);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { diagnostics: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-parts.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z4 } from "npm:zod@^3.25.76";
var search_parts_default = defineTool4({
  name: "search_parts",
  title: "Search equipment parts",
  description: "Search the equipment parts catalog by name, part number, or category and return matching parts with average pricing.",
  inputSchema: {
    query: z4.string().trim().min(1).max(120).describe("Search text matched against part name and part number."),
    category: z4.string().trim().min(1).max(100).optional().describe("Optional category filter."),
    limit: z4.number().int().min(1).max(50).optional().describe("Maximum parts to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const escaped = query.replace(/[%,]/g, " ");
    let request = supabase.from("equipment_parts").select("id, part_number, name, description, category, makes, equipment_types, avg_price").or(`name.ilike.%${escaped}%,part_number.ilike.%${escaped}%`).limit(limit ?? 10);
    if (category) request = request.ilike("category", category);
    const { data, error } = await request;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { parts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-fleet-units.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_fleet_units_default = defineTool5({
  name: "list_fleet_units",
  title: "List fleet units",
  description: "List the signed-in user's fleet units with status and monthly revenue, optionally filtered by status.",
  inputSchema: {
    limit: z5.number().int().min(1).max(100).optional().describe("Maximum units to return (default 25)."),
    status: z5.string().trim().min(1).max(50).optional().describe("Filter by unit status, e.g. 'active'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("fleet_units").select("id, unit_name, unit_type, status, monthly_revenue, acquisition_date, notes").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const totalMonthlyRevenue = (data ?? []).reduce(
      (sum, unit) => sum + Number(unit.monthly_revenue ?? 0),
      0
    );
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify({ units: data ?? [], totalMonthlyRevenue }, null, 2)
        }
      ],
      structuredContent: { units: data ?? [], totalMonthlyRevenue }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "umfsspcknteaocrbveat";
var mcp_default = defineMcp({
  name: "project-hinjd-hub",
  title: "Project Hinjd Hub",
  version: "0.1.0",
  instructions: "Tools for Project Hinjd Hub, an industrial equipment and conveyor operations platform. Use `list_belt_diagnostics` and `create_belt_diagnostic` for conveyor belt tracking issues, `list_equipment_diagnostics` for heavy equipment diagnostic history, `search_parts` to look up parts and pricing, and `list_fleet_units` for fleet status and revenue. All tools act as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_belt_diagnostics_default,
    create_belt_diagnostic_default,
    list_equipment_diagnostics_default,
    search_parts_default,
    list_fleet_units_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
