import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import Stripe from "https://esm.sh/stripe@18.5.0";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.2";
import { PDFDocument, rgb, StandardFonts } from "https://esm.sh/pdf-lib@1.17.1";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, stripe-signature, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version',
};

const logStep = (step: string, details?: unknown) => {
  const detailsStr = details ? ` - ${JSON.stringify(details)}` : '';
  console.log(`[STRIPE-WEBHOOK] ${step}${detailsStr}`);
};

async function generateManifestPdf(order: {
  orderId: string;
  partNumber: string;
  partName: string;
  faultCode: string;
  amount: number;
  customerEmail: string;
  date: string;
}): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([612, 792]); // Letter size
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const { height } = page.getSize();

  const gold = rgb(0.831, 0.686, 0.216); // #D4AF37
  const dark = rgb(0.04, 0.04, 0.04);
  const gray = rgb(0.4, 0.4, 0.4);

  let y = height - 60;

  // Header
  page.drawText('HINJD GLOBAL', { x: 50, y, size: 28, font: boldFont, color: gold });
  y -= 24;
  page.drawText('MORONI HUB — WAREHOUSE MANIFEST', { x: 50, y, size: 14, font: boldFont, color: dark });
  y -= 8;
  page.drawLine({ start: { x: 50, y }, end: { x: 562, y }, thickness: 2, color: gold });
  y -= 30;

  // Order details
  const drawField = (label: string, value: string) => {
    page.drawText(label, { x: 50, y, size: 10, font: boldFont, color: gray });
    page.drawText(value, { x: 200, y, size: 12, font, color: dark });
    y -= 24;
  };

  drawField('ORDER ID:', order.orderId);
  drawField('DATE:', order.date);
  drawField('CUSTOMER:', order.customerEmail);
  y -= 10;
  page.drawLine({ start: { x: 50, y }, end: { x: 562, y }, thickness: 0.5, color: gray });
  y -= 20;

  // Part info
  page.drawText('PART DETAILS', { x: 50, y, size: 14, font: boldFont, color: gold });
  y -= 24;
  drawField('PART NUMBER:', order.partNumber);
  drawField('PART NAME:', order.partName);
  if (order.faultCode) drawField('FAULT CODE:', order.faultCode);
  drawField('ORDER AMOUNT:', `$${order.amount.toFixed(2)}`);

  y -= 10;
  page.drawLine({ start: { x: 50, y }, end: { x: 562, y }, thickness: 0.5, color: gray });
  y -= 20;

  // Revenue split
  page.drawText('REVENUE ALLOCATION', { x: 50, y, size: 14, font: boldFont, color: gold });
  y -= 24;
  drawField('BUSINESS (80%):', `$${(order.amount * 0.8).toFixed(2)}`);
  drawField('SCHOLARSHIP (20%):', `$${(order.amount * 0.2).toFixed(2)}`);

  y -= 20;
  page.drawLine({ start: { x: 50, y }, end: { x: 562, y }, thickness: 0.5, color: gray });
  y -= 30;

  // Shipping
  page.drawText('SHIPPING ADDRESS', { x: 50, y, size: 14, font: boldFont, color: gold });
  y -= 24;
  page.drawText('To be confirmed by customer', { x: 50, y, size: 11, font, color: gray });
  y -= 40;

  // Signature line
  page.drawText('Warehouse Signature: ________________________', { x: 50, y, size: 10, font, color: dark });
  y -= 20;
  page.drawText('Date Shipped: ________________________', { x: 50, y, size: 10, font, color: dark });

  // Footer
  page.drawText('Generated by HINJD Global Ecosystem — Moroni Hub Fulfillment', {
    x: 50, y: 40, size: 8, font, color: gray
  });

  return await pdfDoc.save();
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    logStep('Webhook received');

    const stripeKey = Deno.env.get('STRIPE_SECRET_KEY');
    const webhookSecret = Deno.env.get('STRIPE_WEBHOOK_SECRET');
    
    if (!stripeKey) {
      throw new Error('STRIPE_SECRET_KEY is not configured');
    }

    const stripe = new Stripe(stripeKey, { apiVersion: '2025-08-27.basil' });
    const signature = req.headers.get('stripe-signature');
    const body = await req.text();

    let event: Stripe.Event;

    if (webhookSecret) {
      if (!signature) {
        logStep('Rejected: missing stripe-signature header');
        return new Response(JSON.stringify({ error: 'Missing signature' }), {
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          status: 400,
        });
      }
      try {
        event = stripe.webhooks.constructEvent(body, signature, webhookSecret);
        logStep('Signature verified');
      } catch (err) {
        logStep('Signature verification failed', { error: err });
        return new Response(JSON.stringify({ error: 'Invalid signature' }), {
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          status: 400,
        });
      }
    } else {
      event = JSON.parse(body);
      logStep('WARNING: Processing without signature verification');
    }

    logStep('Event type', { type: event.type });

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
      { auth: { persistSession: false } }
    );

    // Handle payment intent succeeded
    if (event.type === 'payment_intent.succeeded') {
      const paymentIntent = event.data.object as Stripe.PaymentIntent;
      logStep('Payment succeeded', { paymentIntentId: paymentIntent.id });

      const { data, error } = await supabase
        .from('crm_invoices')
        .update({ 
          status: 'paid',
          updated_at: new Date().toISOString()
        })
        .eq('stripe_payment_intent_id', paymentIntent.id)
        .select();

      if (error) {
        logStep('Error updating invoice', { error: error.message });
      } else if (data && data.length > 0) {
        logStep('Invoice updated to paid', { invoiceId: data[0].id });
      } else {
        logStep('No invoice found with payment intent', { paymentIntentId: paymentIntent.id });
      }
    }

    // Handle checkout session completed
    if (event.type === 'checkout.session.completed') {
      const session = event.data.object as Stripe.Checkout.Session;
      logStep('Checkout completed', { sessionId: session.id, orderType: session.metadata?.order_type });

      if (session.metadata?.order_type === 'part_order') {
        const businessRevenue = Number(session.metadata.business_revenue) / 100;
        const scholarshipFund = Number(session.metadata.scholarship_fund) / 100;
        const totalAmount = (session.amount_total || 50000) / 100;

        const { data: txData, error: txError } = await supabase
          .from('hq_transactions')
          .insert({
            user_id: session.metadata.user_id,
            amount: totalAmount,
            business_revenue: businessRevenue,
            scholarship_fund: scholarshipFund,
            transaction_type: 'part_order',
            description: `Part Order: ${session.metadata.part_name} (${session.metadata.part_number})`,
            stripe_payment_intent_id: session.payment_intent as string,
            status: 'completed',
          })
          .select();

        if (txError) {
          logStep('Error logging part order transaction', { error: txError.message });
        } else {
          logStep('Part order transaction logged', { 
            transactionId: txData?.[0]?.id,
            amount: totalAmount,
          });

          // Generate PDF Manifest for Moroni Hub
          try {
            const orderId = txData?.[0]?.id || session.id;
            const pdfBytes = await generateManifestPdf({
              orderId: orderId.slice(0, 8).toUpperCase(),
              partNumber: session.metadata.part_number,
              partName: session.metadata.part_name,
              faultCode: session.metadata.fault_code || '',
              amount: totalAmount,
              customerEmail: session.customer_email || session.customer_details?.email || 'N/A',
              date: new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
            });

            const fileName = `manifest-${orderId.slice(0, 8)}-${Date.now()}.pdf`;
            const { error: uploadError } = await supabase.storage
              .from('manifests')
              .upload(fileName, pdfBytes, {
                contentType: 'application/pdf',
                upsert: false,
              });

            if (uploadError) {
              logStep('Error uploading manifest PDF', { error: uploadError.message });
            } else {
              logStep('Manifest PDF uploaded', { fileName });

              // Save manifest record
              const { error: manifestError } = await supabase
                .from('order_manifests')
                .insert({
                  user_id: session.metadata.user_id,
                  transaction_id: txData?.[0]?.id || null,
                  part_number: session.metadata.part_number,
                  part_name: session.metadata.part_name,
                  order_amount: totalAmount,
                  pdf_url: fileName,
                  status: 'generated',
                });

              if (manifestError) {
                logStep('Error saving manifest record', { error: manifestError.message });
              } else {
                logStep('Manifest record saved');
              }
            }
          } catch (pdfError) {
            logStep('Error generating manifest PDF', { error: String(pdfError) });
          }
        }
      } else if (session.payment_intent) {
        const { data, error } = await supabase
          .from('crm_invoices')
          .update({ 
            status: 'paid',
            stripe_payment_intent_id: session.payment_intent as string,
            updated_at: new Date().toISOString()
          })
          .eq('id', session.metadata?.invoice_id)
          .select();

        if (error) {
          logStep('Error updating invoice from checkout', { error: error.message });
        } else if (data && data.length > 0) {
          logStep('Invoice updated from checkout', { invoiceId: data[0].id });
        }
      }
    }

    // Handle invoice paid (for subscriptions)
    if (event.type === 'invoice.paid') {
      const invoice = event.data.object as Stripe.Invoice;
      logStep('Invoice paid', { invoiceId: invoice.id });
    }

    return new Response(JSON.stringify({ received: true }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 200,
    });
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    logStep('ERROR', { message: errorMessage });
    return new Response(JSON.stringify({ error: errorMessage }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 500,
    });
  }
});
